apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-chart.fullname" . }}
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "django-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "django-chart.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      {{- if .Values.imagePullSecrets.name }}
        - name: {{ .Values.imagePullSecrets.name }}
      {{- else }}
        - name: {{ include "django-chart.fullname" . }}-regcred
      {{- end }}
      serviceAccountName: {{ include "django-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  {{- if .Values.postgresql.credentials.name }}
                  name: {{ .Values.postgresql.credentials.name }}
                  {{- else }}
                  name: {{ include "django-chart.fullname" . }}-pgcred
                  {{- end }}
                  key: pgusername
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  {{- if .Values.postgresql.credentials.name }}
                  name: {{ .Values.postgresql.credentials.name }}
                  {{- else }}
                  name: {{ include "django-chart.fullname" . }}-pgcred
                  {{- end }}
                  key: pgdbname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.postgresql.credentials.name }}
                  name: {{ .Values.postgresql.credentials.name }}
                  {{- else }}
                  name: {{ include "django-chart.fullname" . }}-pgcred
                  {{- end }}
                  key: pgpassword
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  {{- if .Values.postgresql.credentials.name }}
                  name: {{ .Values.postgresql.credentials.name }}
                  {{- else }}
                  name: {{ include "django-chart.fullname" . }}-pgcred
                  {{- end }}
                  key: pghost
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  {{- if .Values.postgresql.credentials.name }}
                  name: {{ .Values.postgresql.credentials.name }}
                  {{- else }}
                  name: {{ include "django-chart.fullname" . }}-pgcred
                  {{- end }}
                  key: pgport
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
