apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-chart.fullname" . }}-pgcred
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
type: Opaque
data:
  dbname: {{ .Values.postgresql.global.postgresql.postgresqlDatabase | b64enc }}
  {{- if .Values.postgresql.host }}
  host: {{ .Values.postgresql.host | b64enc }}
  {{- else }}
  host: {{ .Values.postgresql.defaulthost | b64enc }}
  {{- end }}
  password: {{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc }}
  port: {{ .Values.postgresql.global.postgresql.port | toString | b64enc }}
  username: {{ .Values.postgresql.global.postgresql.postgresqlUsername | b64enc }}