{{- if .Values.postgresql.credentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-chart.fullname" . }}-pgcred
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
type: Opaque
data:
  pgdbname: {{ .Values.postgresql.global.postgresql.postgresqlDatabase | b64enc }}
  {{- if .Values.postgresql.host }}
  pghost: {{ .Values.postgresql.host | b64enc }}
  {{- else }}
  pghost: {{ .Values.postgresql.defaulthost | b64enc }}
  {{- end }}
  pgpassword: {{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc }}
  pgport: {{ .Values.postgresql.global.postgresql.port | toString | b64enc }}
  pgusername: {{ .Values.postgresql.global.postgresql.postgresqlUsername | b64enc }}
{{- end }}