{{- if .Values.imagePullSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-chart.fullname" . }}-regcred
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}