{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "django-chart.serviceAccountName" . }}
  labels:
{{- include "django-chart.labels" . | nindent 4 }}
{{- end -}}